# Generated by Django 3.2.20 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_alter_assign_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ptitle',
            field=models.TextField(),
        ),
    ]
